const data = [
    {
      id: 1,
      title: 'buttermilk  pancakes ',
      category: 'breakfast',
      price: 15.99,
      img:'https://th.bing.com/th/id/OIP.NNayoWDos5H4gpArTagIDQHaJQ?pid=ImgDet&rs=1',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 2,
      title: 'diner double',
      category: 'lunch',
      price: 13.99,
      img: 'https://th.bing.com/th/id/OIP.IG9bp_48uID2Bc7d8e-ZcgHaEK?pid=ImgDet&w=1920&h=1080&rs=1',
      desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
    },
    {
      id: 3,
      title: 'godzilla milkshake',
      category: 'shakes',
      price: 6.99,
      img: 'https://recipes.timesofindia.com/thumb/53806438.cms?imgsize=135050&width=800&height=800',
      desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
    },
    {
      id: 4,
      title: 'country delight',
      category: 'breakfast',
      price: 20.99,
      img: 'https://www.hospibuz.com/wp-content/uploads/2021/04/CHEF-93.jpg',
      desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
    },
    {
      id: 5,
      title: 'egg attack',
      category: 'lunch',
      price: 22.99,
      img: 'https://th.bing.com/th/id/OIP.TflFQvphjX7OI-GZ82jc8wHaFj?pid=ImgDet&rs=1',
      desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
    },
    {
      id: 6,
      title: 'oreo dream',
      category: 'shakes',
      price: 18.99,
      img: 'https://th.bing.com/th/id/OIP.myPwrgF1r-YgN-DtCEAm5QHaE8?pid=ImgDet&rs=1',
      desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    },
    {
      id: 7,
      title: 'bacon overflow',
      category: 'breakfast',
      price: 8.99,
      img:"https://th.bing.com/th/id/OIP.kCr2OoekzDS8uJANJZkU_gHaFj?pid=ImgDet&rs=1",
      desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
    },
    {
      id: 8,
      title: 'american classic',
      category: 'lunch',
      price: 12.99,
      img: "https://th.bing.com/th/id/R.b79348fba40a1f272346697df9e715f9?rik=RrSQvR8HNnZaXQ&riu=http%3a%2f%2ffoodfornet.s3.amazonaws.com%2fwp-content%2fuploads%2f2015%2f06%2fshutterstock_243241513.jpg&ehk=K8g65PT9wBxQ3bLzVPk19QA4V7un4e74N8ryK4U5L58%3d&risl=&pid=ImgRaw&r=0",
      desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
    },
    {
      id: 9,
      title: 'quarantine buddy',
      category: 'shakes',
      price: 16.99,
      img: "https://lh3.googleusercontent.com/proxy/OjD8kc3ixAt47bq_uCFIPiKzndFCqtK5z3En_XPHvcIQkRRarJbuMDr2ALIjc-E72wPsXt7kQ2LDX8gmtiOn-v3zi4Mo7ybqPHnz0m0evqyzyzKB_WCTKk2MBPg-sqpZLD5UKoMFVfNTXgeQBf4Zi3_YjsUiJHWLAkie=w1200-h630-p-k-no-nu",
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
    
  ];
  export default data;